  name: login_screen
  description: "A new Flutter project."
  publish_to: 'none'

  version: 1.0.0+1

  environment:
    sdk: '>=3.4.0 <4.0.0'

  dependencies:
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.6
    flutter_svg: ^2.0.10+1
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    path_provider: ^2.1.3

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^3.0.0
    hive_generator: ^2.0.1
    build_runner: ^2.4.11

  flutter:
    uses-material-design: true

    assets:
      - assets/images/logo.svg
      - assets/images/icon_facebook.svg
      - assets/images/icon_headphone.svg
      - assets/images/icon_search.svg
      - assets/images/icon_close.svg
      

    # fonts:
      # - family: NunitoSans
        # fonts:
          # - asset: assets/fonts/NunitoSans-SemiBold.ttf